# Generated by Django 5.1.2 on 2024-10-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='train_number',
            field=models.IntegerField(),
        ),
    ]
