# Generated by Django 5.1.2 on 2024-10-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_train_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='date_of_journey',
        ),
    ]
